import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/common/Navbar";
import Footer from "./Components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-black text-white`}
      >
        {/* Navbar at top */}
        <div className="sticky top-0 z-50 shadow-md">
          <Navbar />
        </div>


        {/* Main content takes all remaining height */}
        <main className="flex-1">{children}</main>

        {/* Footer sticks to bottom */}
        <Footer />
      </body>
    </html>
  );
}
